services:
  db:
    image: ${POSTGRES_IMAGE}
    user: root
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"  # Puerto PostgreSQL desde la variable de entorno
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo:
#    build:
#      context: ./odoo/build/
#      dockerfile: DockerfileOdoo
    image: odoo:17
    container_name: odoo17_app
    depends_on:
      - db      
    devices:
      - "/dev/fuse"
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_LONGPOLLING_PORT}:8072"
    tty: true
    environment:
      - HOST=postgres_db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}      
    volumes:
      - ./odoo/odoo-data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/etc:/etc/odoo
      #- ./odoo/build/entrypoint.sh:/entrypoint.sh
    #command: /entrypoint.sh

    restart: always