services:
  db:
    image: ${POSTGRES_IMAGE}
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo17:
    image: ${ODOO_IMAGE}
    container_name: odoo17_app
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_LONGPOLLING_PORT}:8072"
    tty: true
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
